version: 2

models:
  - name: DIM_agent
    description: "Agent dimension table"
    columns:
      - name: agent_sk
        description: "Surrogate key for agent"
        data_tests:
          - not_null
          - unique

      - name: agent_id
        description: "Natural key for agent"
        data_tests:
          - not_null

      - name: agent_name
        description: "Name of the agent"
        data_tests:
          - not_null

      - name: department
        description: "Department the agent belongs to"
        data_tests:
          - not_null

      - name: status
        description: "Employment status of the agent"
        data_tests:
          - not_null

  - name: DIM_cell_site
    description: "Cell site dimension table"
    columns:
      - name: cell_site_sk
        description: "Surrogate key for cell site"
        data_tests:
          - not_null
          - unique

      - name: cell_id
        description: "Natural key for cell site"
        data_tests:
          - not_null

      - name: cell_site_name
        description: "Name of the cell site"
        data_tests:
          - not_null

      - name: city
        description: "City where the cell site is located"
        data_tests:
          - not_null

      - name: latitude
        description: "Latitude of the cell site"
        data_tests:
          - not_null

      - name: longitude
        description: "Longitude of the cell site"
        data_tests:
          - not_null

  - name: DIM_Device
    description: "Device dimension table"
    columns:
      - name: device_sk
        description: "Surrogate key for device"
        data_tests:
          - not_null
          - unique

      - name: tac
        description: "Type Allocation Code for the device"
        data_tests:
          - not_null

      - name: brand
        description: "Brand of the device"
        data_tests:
          - not_null

      - name: model
        description: "Model of the device"
        data_tests:
          - not_null

      - name: imei
        description: "International Mobile Equipment Identity number"
        data_tests:
          - not_null

  - name: DIM_Users
    description: "Users dimension table"
    columns:
      - name: user_sk
        description: "Surrogate key for user"
        data_tests:
          - not_null
          - unique

      - name: phone_number
        description: "Phone number of the user"
        data_tests:
          - not_null

      - name: city
        description: "City where the user is located"
        data_tests:
          - not_null

      - name: status
        description: "Status of the user (e.g., active, inactive)"
        data_tests:
          - not_null

      - name: customer_type
        description: "Type of customer (e.g., residential, business)"
        data_tests:
          - not_null
        
      - name: gender
        description: "Gender of the user"
        data_tests:
          - not_null

      - name: age_group
        description: "Age group of the user"
        data_tests:
          - not_null

  - name: DIM_Time
    description: "Time dimension table"
    columns:
      - name: time_sk
        description: "Surrogate key for time"
        data_tests:
          - not_null
          - unique

      - name: hour_of_day
        description: "Hour of the day (0-23)"
        data_tests:
          - not_null

      - name: minute_of_hour
        description: "Minute of the hour (0-59)"
        data_tests:
          - not_null

      - name: am_pm
        description: "AM or PM indicator"
        data_tests:
          - not_null

      - name: hour_12
        description: "Hour in 12-hour format (1-12)"
        data_tests:
          - not_null

      - name: time_24hr
        description: "Time in 24-hour format (00:00-23:59)"
        data_tests:
          - not_null

  - name: DIM_Date
    description: "Date dimension table"
    columns:
      - name: date_sk
        description: "Surrogate key for date"
        data_tests:
          - not_null
          - unique

      - name: date_series
        description: "Date in YYYY-MM-DD format from 2026-01-01 to 2026-12-31"
        data_tests:
          - not_null

      - name: year
        description: "Year (e.g., 2026)"
        data_tests:
          - not_null

      - name: month
        description: "Month of the year (1-12)"
        data_tests:
          - not_null

      - name: quarter
        description: "Quarter of the year (1-4)"
        data_tests:
          - not_null

      - name: day
        description: "Day of the month (1-31)"
        data_tests:
          - not_null
      
      - name: month_name
        description: "Name of the month (e.g., January)"
        data_tests:
          - not_null
        
      - name: day_of_year
        description: "Day of the year (1-366)"
        data_tests:
          - not_null
      
      - name: day_name
        description: "Name of the day (e.g., Monday)"
        data_tests:
          - not_null

      - name: week_of_year
        description: "Week of the year (1-53)"
        data_tests:
          - not_null
      
      - name: is_weekend
        description: "Indicator if the date is a weekend (true/false)"
        data_tests:
          - not_null
      
      - name: first_day_of_month
        description: "Indicator if the date is the first day of the month (true/false)"
        data_tests:
          - not_null

      - name: last_day_of_month
        description: "Indicator if the date is the last day of the month (true/false)"
        data_tests:
          - not_null

      

      